version: '3.8'
services:
  nest:
    build: ./backend
    ports:
      - '${BACKEND_PORT}:3000'
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      MONGODB_HOST: ${MONGODB_HOST}
      MONGODB_PORT: ${MONGODB_PORT}
      MONGODB_USER: ${MONGODB_USER}
      MONGODB_PASSWORD: ${MONGODB_PASSWORD}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    networks:
      - mongo-compose-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    restart: always
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - ./database/mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mongo-compose-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
      
networks: 
    mongo-compose-network:
      driver: bridge
volumes:
  mongodb_data:
    driver: local